import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 12,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleCol: {
    flex: 1,
  },
  headerSongTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0f172a',
    flexShrink: 1,
  },
  headerSubtitle: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  statusBadgePending: {
    backgroundColor: '#fffbeb',
  },
  statusBadgeApproved: {
    backgroundColor: '#ecfdf5',
  },
  statusBadgeRejected: {
    backgroundColor: '#fff1f2',
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '800',
  },
  statusBadgeTextPending: {
    color: '#b45309',
  },
  statusBadgeTextApproved: {
    color: '#047857',
  },
  statusBadgeTextRejected: {
    color: '#e11d48',
  },
  audioPlayerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd6fe',
    gap: 10,
  },
  audioPlayBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#7c3aed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  audioTitleText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f172a',
  },
  audioMetaText: {
    fontSize: 10,
    color: '#6b21a8',
  },
  openExternalBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  openExternalText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7c3aed',
  },
  tabsRow: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 6,
  },
  tabBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#f8fafc',
  },
  tabBtnActive: {
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  tabBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
  },
  tabBtnTextActive: {
    color: '#7c3aed',
    fontWeight: '800',
  },
  chatScroll: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  chatContent: {
    padding: 14,
    gap: 12,
  },
  emptyChatBox: {
    paddingVertical: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  emptyChatTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748b',
  },
  emptyChatSub: {
    fontSize: 11,
    color: '#94a3b8',
    textAlign: 'center',
    maxWidth: 240,
  },
  chatBubbleWrap: {
    maxWidth: '85%',
  },
  chatWrapRight: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
  },
  chatWrapLeft: {
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
  },
  chatMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
    paddingHorizontal: 4,
  },
  chatSenderName: {
    fontSize: 10,
    fontWeight: '700',
    color: '#64748b',
  },
  chatTimeText: {
    fontSize: 9.5,
    color: '#94a3b8',
  },
  chatBubble: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chatBubbleAdmin: {
    backgroundColor: '#7c3aed',
    borderBottomRightRadius: 2,
  },
  chatBubbleUser: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderBottomLeftRadius: 2,
  },
  chatMessageText: {
    fontSize: 12.5,
    lineHeight: 18,
  },
  chatMessageTextAdmin: {
    color: '#ffffff',
  },
  chatMessageTextUser: {
    color: '#0f172a',
  },
  replyPreviewCard: {
    borderLeftWidth: 2,
    paddingLeft: 6,
    paddingVertical: 2,
    marginBottom: 4,
  },
  replyPreviewAdmin: {
    borderLeftColor: '#ddd6fe',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  replyPreviewUser: {
    borderLeftColor: '#7c3aed',
    backgroundColor: '#f8fafc',
  },
  replyPreviewSender: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#cbd5e1',
  },
  replyPreviewText: {
    fontSize: 10.5,
    fontStyle: 'italic',
    color: '#e2e8f0',
  },
  reactionsRow: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 4,
  },
  reactionPill: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  reactionText: {
    fontSize: 10,
    color: '#ffffff',
  },
  replyActionTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    paddingHorizontal: 4,
  },
  replyActionText: {
    fontSize: 10,
    color: '#94a3b8',
  },
  quickChipsBar: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingVertical: 6,
  },
  quickChipsScroll: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
  },
  quickChip: {
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 9,
    paddingVertical: 4.5,
    borderRadius: 8,
  },
  quickChipText: {
    fontSize: 11,
    color: '#475569',
    fontWeight: '600',
  },
  replyingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: '#ddd6fe',
  },
  replyingToTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: '#7c3aed',
  },
  replyingToSnippet: {
    fontSize: 11,
    color: '#64748b',
    fontStyle: 'italic',
  },
  composerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 8,
  },
  composerInput: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 12,
    height: 38,
    fontSize: 12.5,
    color: '#0f172a',
  },
  sendBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#7c3aed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    opacity: 0.4,
  },
  bodyScroll: {
    flex: 1,
  },
  bodyContent: {
    padding: 16,
    gap: 12,
  },
  contentCard: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  cardHeaderTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0f172a',
  },
  copyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
  },
  copyBtnText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#7c3aed',
  },
  lyricsText: {
    fontSize: 13,
    lineHeight: 22,
    color: '#1e293b',
  },
  solfaText: {
    fontSize: 12.5,
    lineHeight: 20,
    color: '#1e293b',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  notesText: {
    fontSize: 12.5,
    lineHeight: 19,
    color: '#475569',
  },
  bottomActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingHorizontal: 14,
    paddingTop: 10,
    gap: 8,
  },
  declineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff1f2',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  declineBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#e11d48',
  },
  revisionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fffbeb',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  revisionBtnText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#b45309',
  },
  approveBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10b981',
    paddingVertical: 9,
    borderRadius: 10,
  },
  approveBtnText: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#ffffff',
  },
  reviewedNoticeBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
  },
  reviewedNoticeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  rejectCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    width: '100%',
    maxWidth: 380,
    gap: 10,
  },
  rejectCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rejectCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
  },
  rejectCardSub: {
    fontSize: 11.5,
    color: '#64748b',
    lineHeight: 16,
  },
  rejectTextInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 10,
    height: 80,
    fontSize: 12.5,
    color: '#0f172a',
    textAlignVertical: 'top',
  },
  rejectActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  },
  rejectCancelBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
  },
  rejectCancelBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  rejectConfirmBtn: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#e11d48',
  },
  rejectConfirmBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },
});
