import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  webHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  webHeaderTitleWrap: {
    flex: 1,
    marginRight: 12,
  },
  webHeaderTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: -0.3,
  },
  webHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerDeleteBtn: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#fef2f2',
  },
  headerCloseBtn: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#f8fafc',
  },
  scrollBody: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContent: {
    padding: 16,
  },
  scrollContentDesktop: {
    paddingHorizontal: 24,
    maxWidth: 1400,
    alignSelf: 'center',
    width: '100%',
  },

  // ── Desktop Two-Column Grid (col-span-2 / col-span-3) ─────────────────────
  desktopTwoColContainer: {
    flexDirection: 'row',
    gap: 24,
    alignItems: 'flex-start',
  },
  desktopLeftCol: {
    flex: 2,
    gap: 16,
  },
  desktopRightCol: {
    flex: 3,
    gap: 16,
  },

  // ── Gray Slate Cards (Cards 1, 2, 3, 4) ──────────────────────────────────
  cardSlate: {
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  cardHeaderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    letterSpacing: -0.2,
  },
  cardHeaderSub: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 2,
  },
  addHistoryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#f1f5f9',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  addHistoryBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },

  // ── Form Inputs ──────────────────────────────────────────────────────────
  fieldGroup: {
    marginBottom: 12,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
    marginBottom: 6,
  },
  inputPrimary: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: '#0f172a',
  },
  inputLarge: {
    fontSize: 16,
    fontWeight: '600',
    paddingVertical: 12,
  },
  fieldRowResponsive: {
    flexDirection: 'row',
    gap: 12,
  },
  threeColRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  personnelGrid: {
    gap: 10,
    justifyContent: 'space-between',
  },

  // ── Categories Checkboxes Box ────────────────────────────────────────────
  categoriesHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  addCategoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  addCategoryPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7c3aed',
  },
  clearCategoriesPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    paddingHorizontal: 8,
    paddingVertical: 3.5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  clearCategoriesPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#dc2626',
  },
  categoryCheckboxRowNoneActive: {
    backgroundColor: '#ecfdf5',
  },
  newCategoryInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
    borderRadius: 8,
    padding: 6,
    marginBottom: 8,
  },
  newCategoryTextInput: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12.5,
    color: '#0f172a',
  },
  addCategoryConfirmBtn: {
    backgroundColor: '#7c3aed',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 6,
  },
  addCategoryConfirmBtnText: {
    color: '#ffffff',
    fontSize: 11.5,
    fontWeight: '700',
  },
  addCategoryCancelBtn: {
    padding: 6,
  },
  categoriesCheckboxContainer: {
    backgroundColor: '#f8fafc',
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    padding: 4,
    maxHeight: 180,
    overflow: 'hidden',
  },
  categoryCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 7,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  categoryCheckboxText: {
    fontSize: 13,
    color: '#334155',
  },
  categoryCheckboxTextActive: {
    fontWeight: '700',
    color: '#7c3aed',
  },
  selectedCategoriesSummary: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 6,
  },

  // ── Select Trigger Dropdown ──────────────────────────────────────────────
  pickerTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  pickerTriggerText: {
    fontSize: 13.5,
    fontWeight: '500',
    color: '#0f172a',
  },

  // ── Song Artwork ─────────────────────────────────────────────────────────
  artworkSectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  artworkPreviewWrap: {
    position: 'relative',
    width: 88,
    height: 88,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#e2e8f0',
  },
  artworkImg: {
    width: '100%',
    height: '100%',
  },
  artworkRemoveBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  artworkPlaceholder: {
    width: 88,
    height: 88,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  artworkPlaceholderText: {
    fontSize: 10,
    color: '#94a3b8',
    fontWeight: '600',
  },
  selectArtworkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  selectArtworkBtnText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#334155',
  },
  artworkHintText: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 6,
    lineHeight: 15,
  },

  // ── Audio File Player Box ────────────────────────────────────────────────
  browseMediaPrimaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c3aed',
    borderRadius: 8,
    paddingVertical: 11,
    paddingHorizontal: 16,
  },
  browseMediaPrimaryBtnText: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#ffffff',
  },
  audioFilePlayerBox: {
    marginTop: 10,
    padding: 12,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  audioFileMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  audioDotPurple: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8b5cf6',
  },
  audioFileName: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  audioFileSizeText: {
    fontSize: 11,
    color: '#64748b',
    marginLeft: 16,
    marginTop: 2,
    marginBottom: 8,
  },
  inlinePlayerBar: {
    marginTop: 4,
  },
  miniPlayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  miniPlayBtnActive: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  miniPlayBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7c3aed',
  },
  miniPlayBtnTextActive: {
    color: '#ffffff',
  },

  // ── AudioLab Multi-Stem Grid ─────────────────────────────────────────────
  addCustomPartPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  addCustomPartPillText: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#7c3aed',
  },
  addCustomPartInputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
    borderRadius: 10,
    padding: 8,
    marginBottom: 12,
  },
  addCustomPartInput: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 12.5,
  },
  addPartBtn: {
    backgroundColor: '#7c3aed',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
  },
  addPartBtnText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  cancelPartBtn: {
    padding: 6,
  },
  stemsContainer: {
    gap: 10,
    justifyContent: 'space-between',
  },
  stemCard: {
    borderRadius: 10,
    borderWidth: 2,
    padding: 10,
  },
  stemCardEmpty: {
    backgroundColor: '#ffffff',
    borderColor: '#e2e8f0',
  },
  stemCardCustomEmpty: {
    backgroundColor: '#fffaf5',
    borderColor: '#fed7aa',
  },
  stemCardUploaded: {
    backgroundColor: '#f0fdf4',
    borderColor: '#86efac',
  },
  stemCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  stemCardLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#334155',
  },
  stemCardLabelUploaded: {
    color: '#15803d',
    fontWeight: '700',
  },
  stemAudioActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stemPlayTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#dcfce7',
  },
  stemPlayTouchActive: {
    backgroundColor: '#16a34a',
  },
  stemPlayTouchText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16a34a',
  },
  stemPlayTouchTextActive: {
    color: '#ffffff',
  },
  stemTrashBtn: {
    padding: 4,
  },
  selectFromMediaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  selectFromMediaBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#475569',
  },

  // ── White Cards with Distinct Header Bar (Cards 5, 6, 7) ─────────────────
  cardWhiteWithHeader: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  cardWhiteHeaderBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  dotMarker: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  cardWhiteBody: {
    padding: 14,
  },
  helperBanner: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 6,
    padding: 8,
    marginBottom: 10,
  },
  helperBannerText: {
    fontSize: 11,
    color: '#64748b',
  },
  multilineEditor: {
    minHeight: 110,
    fontSize: 13.5,
    lineHeight: 20,
  },
  fontMono: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 12.5,
  },

  // ── Coordinator Comments Voice Note ──────────────────────────────────────
  subFieldUppercase: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  voiceNoteCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
    borderRadius: 10,
    padding: 10,
  },
  voiceNoteTitle: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#6d28d9',
  },
  addVoiceNoteTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    paddingVertical: 10,
  },
  addVoiceNoteTouchText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#64748b',
  },

  // ── Footer ───────────────────────────────────────────────────────────────
  webFooter: {
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  footerRowTablet: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  footerUpdateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c3aed',
    borderRadius: 8,
    paddingVertical: 13,
  },
  footerUpdateBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  footerSecondaryRow: {
    flexDirection: 'row',
    gap: 8,
  },
  footerHistoryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c3aed',
    borderRadius: 8,
    paddingVertical: 10,
    position: 'relative',
  },
  footerHistoryBtnTablet: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7c3aed',
    borderRadius: 8,
    paddingVertical: 13,
    paddingHorizontal: 18,
    position: 'relative',
  },
  footerHistoryBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  footerHistoryBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footerHistoryBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#ffffff',
  },
  footerCancelBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingVertical: 10,
  },
  footerCancelBtnTablet: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    paddingVertical: 13,
    paddingHorizontal: 20,
  },
  footerCancelBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },

  // ── Picker & History Modals ──────────────────────────────────────────────
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'flex-end',
  },
  pickerModalContent: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  pickerModalContentCentered: {
    borderRadius: 20,
    marginHorizontal: 24,
    marginBottom: 'auto',
    marginTop: 'auto',
    maxWidth: 500,
    alignSelf: 'center',
    width: '100%',
  },
  pickerModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 14,
  },
  pickerOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  pickerOptionText: {
    fontSize: 14,
    color: '#334155',
  },
  pickerOptionTextActive: {
    fontWeight: '700',
    color: '#7c3aed',
  },
  historyListSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
  },
  historySheetCentered: {
    borderRadius: 20,
    marginHorizontal: 24,
    marginBottom: 'auto',
    marginTop: 'auto',
    maxWidth: 560,
    alignSelf: 'center',
    width: '100%',
    paddingBottom: 20,
  },
  historySheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  historySheetTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  historyRowItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  historyRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  historyRowType: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7c3aed',
    textTransform: 'uppercase',
  },
  historyRowDate: {
    fontSize: 11,
    color: '#94a3b8',
  },
  historyRowTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: '#0f172a',
  },
  historyRowDesc: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  historyDeleteTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  historyDeleteText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#ef4444',
  },
  closeHistorySheetBtn: {
    marginHorizontal: 16,
    marginTop: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
  },
  closeHistorySheetBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },

  // ── Header LIVE Broadcast Pill ───────────────────────────────────────────
  headerLivePill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  headerLivePillActive: {
    backgroundColor: '#ffe4e6',
    borderColor: '#f43f5e',
  },
  headerLivePillInactive: {
    backgroundColor: '#f1f5f9',
    borderColor: '#cbd5e1',
  },
  headerLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#94a3b8',
    marginRight: 5,
  },
  headerLiveDotActive: {
    backgroundColor: '#e11d48',
  },
  headerLiveText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748b',
  },
  headerLiveTextActive: {
    color: '#e11d48',
  },

  // ── Card 1 Broadcast Status Toggle ───────────────────────────────────────
  broadcastRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
  },
  broadcastSubtext: {
    fontSize: 11.5,
    color: '#64748b',
    marginTop: 1,
  },
  hqOnlyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#faf5ff',
    borderWidth: 1,
    borderColor: '#e9d5ff',
    borderRadius: 10,
    padding: 12,
    marginTop: 10,
  },
  liveToggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1.5,
  },
  liveToggleBtnActive: {
    backgroundColor: '#ffe4e6',
    borderColor: '#e11d48',
  },
  liveToggleBtnInactive: {
    backgroundColor: '#f8fafc',
    borderColor: '#cbd5e1',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#94a3b8',
    marginRight: 6,
  },
  liveDotActive: {
    backgroundColor: '#e11d48',
  },
  liveToggleBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#64748b',
  },
  liveToggleBtnTextActive: {
    color: '#e11d48',
  },

  // ── Web Admin Revision History Styles ────────────────────────────────────
  webHistoryCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
  },
  webHistoryCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  webHistoryTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  webHistoryTypeBadge: {
    backgroundColor: '#dbeafe',
    paddingHorizontal: 8,
    paddingVertical: 2.5,
    borderRadius: 999,
  },
  webHistoryTypeBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1e40af',
  },
  webHistoryDateText: {
    fontSize: 12,
    color: '#64748b',
  },
  webHistoryTitleText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 2,
  },
  webHistoryDescText: {
    fontSize: 12.5,
    color: '#475569',
    marginBottom: 4,
  },
  webHistoryAuthorText: {
    fontSize: 11,
    color: '#94a3b8',
  },
  webHistoryActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 10,
  },
  webHistoryEditBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  webHistoryDeleteBtn: {
    padding: 6,
    borderRadius: 6,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  historySheetSubtitle: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  historyTypeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  singleTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#dbeafe',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  singleTypeBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1e40af',
  },
  historyTypeSelectChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  historyTypeSelectChipActive: {
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  historyTypeSelectChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  historyTypeSelectChipTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  webHistoryInfoCallout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    borderRadius: 8,
    padding: 12,
    marginTop: 4,
  },
  webHistoryInfoCalloutText: {
    flex: 1,
    fontSize: 12,
    color: '#1e40af',
    lineHeight: 17,
  },
  historyFormActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    marginTop: 8,
  },
  historyFormCancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
  },
  historyFormCancelBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
  },
  historyFormSaveBtn: {
    paddingHorizontal: 18,
    paddingVertical: 9,
    borderRadius: 8,
    backgroundColor: '#16a34a',
  },
  historyFormSaveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },

  // ── Segmented Tab Bar ─────────────────────────────────────────────────────
  tabBarContainer: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tabBarScrollContent: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 4,
  },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  tabItemActive: {
    backgroundColor: '#f5f3ff',
    borderColor: '#c4b5fd',
  },
  tabItemText: {
    fontSize: 12.5,
    fontWeight: '600',
    color: '#64748b',
  },
  tabItemTextActive: {
    color: '#7c3aed',
  },
  tabBadgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#94a3b8',
    marginLeft: 5,
  },
  tabBadgeDotActive: {
    backgroundColor: '#7c3aed',
  },
  tabCountBadge: {
    marginLeft: 5,
    backgroundColor: '#7c3aed',
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  tabCountBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#ffffff',
  },

  // ── Header Quick Save Button ──────────────────────────────────────────────
  headerQuickSaveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#7c3aed',
  },
  headerQuickSaveBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },

  // ── Full Screen Expand Button (in Lyrics card header) ────────────────────
  fullscreenBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#f5f3ff',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#c4b5fd',
  },
  fullscreenBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#7c3aed',
  },

  // ── Expanded multiline editor when on Lyrics tab ──────────────────────────
  multilineEditorTabActive: {
    minHeight: 320,
  },

  // ── Fullscreen Lyrics Editor Modal ────────────────────────────────────────
  fullscreenLyricsRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  fullscreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  fullscreenCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenHeaderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  fullscreenHeaderSub: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 1,
  },
  fullscreenDoneBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  fullscreenDoneBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  fullscreenToolbarWrap: {
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  fullscreenInput: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    color: '#0f172a',
    textAlignVertical: 'top',
    backgroundColor: '#ffffff',
  },
  fontStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    overflow: 'hidden',
  },
  fontStepBtn: {
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  fontStepBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  fontStepValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0f172a',
    paddingHorizontal: 4,
    minWidth: 24,
    textAlign: 'center',
  },
});
