import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
  },
  backdrop: {
    ...StyleSheet.absoluteFill,
  },
  sheet: {
    backgroundColor: '#f8fafc',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '92%',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 10,
  },
  grabBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#cbd5e1',
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  headerTitle: { fontSize: 16, fontWeight: '900', color: '#0f172a' },
  headerSub: { fontSize: 11, color: '#64748b', marginTop: 1 },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: { paddingHorizontal: 16, paddingTop: 12 },
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 10,
  },
  avatarWrap: { position: 'relative', marginRight: 12 },
  avatarImg: { width: 50, height: 50, borderRadius: 18 },
  avatarFallback: {
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: '#7c3aed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 18, fontWeight: '900', color: '#ffffff' },
  onlineDot: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10b981',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  heroMeta: { flex: 1 },
  heroNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  heroName: { fontSize: 15, fontWeight: '900', color: '#0f172a', flexShrink: 1 },
  aliasPill: {
    fontSize: 10,
    fontWeight: '800',
    color: '#4338ca',
    backgroundColor: '#eef2ff',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
  },
  heroEmail: { fontSize: 11, color: '#64748b', marginTop: 1 },
  zoneFixedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  zoneFixedText: { fontSize: 10, fontWeight: '700', color: '#475569' },
  pendingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fffbeb',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fde68a',
    marginBottom: 10,
  },
  pendingTitle: { fontSize: 12, fontWeight: '800', color: '#92400e' },
  pendingSub: { fontSize: 10, color: '#b45309', marginTop: 1 },
  pendingBtnRow: { flexDirection: 'row', gap: 6 },
  approveBtn: { backgroundColor: '#10b981', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  approveBtnText: { fontSize: 11, fontWeight: '800', color: '#ffffff' },
  declineBtn: { backgroundColor: '#fee2e2', paddingHorizontal: 8, paddingVertical: 6, borderRadius: 8 },
  declineBtnText: { fontSize: 11, fontWeight: '800', color: '#b91c1c' },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 10,
  },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  cardHeading: {
    fontSize: 12,
    fontWeight: '900',
    color: '#0f172a',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cardHint: { fontSize: 11, color: '#64748b', marginTop: 2 },
  statusSubText: { fontSize: 11, fontWeight: '800', marginTop: 2 },
  textActive: { color: '#10b981' },
  textInactive: { color: '#ef4444' },
  passesList: { borderTopWidth: 1, borderTopColor: '#f1f5f9', marginTop: 10, paddingTop: 4 },
  passRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f8fafc',
  },
  passTitle: { fontSize: 12, fontWeight: '800', color: '#0f172a' },
  passSub: { fontSize: 10, color: '#64748b', marginTop: 1 },
  passTagAmber: { backgroundColor: '#fef3c7', paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4 },
  passTagAmberText: { fontSize: 9, fontWeight: '800', color: '#b45309' },
  passTagIndigo: { backgroundColor: '#eef2ff', paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4 },
  passTagIndigoText: { fontSize: 9, fontWeight: '800', color: '#4338ca' },
  inputLabel: { fontSize: 11, fontWeight: '800', color: '#64748b', marginBottom: 4 },
  roleOptionsList: { marginTop: 8, borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  roleOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  roleOptionRowActive: {
    backgroundColor: '#faf5ff',
    marginHorizontal: -10,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  roleRadioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  roleRadioCircleActive: { borderColor: '#7c3aed' },
  roleRadioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#7c3aed' },
  roleTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  roleTitleText: { fontSize: 13, fontWeight: '800', color: '#334155' },
  roleTitleTextActive: { color: '#7c3aed', fontWeight: '900' },
  roleSubText: { fontSize: 11, color: '#64748b', marginTop: 1 },
  rolePillSlate: { backgroundColor: '#f1f5f9', paddingHorizontal: 6, paddingVertical: 1, borderRadius: 6 },
  rolePillSlateText: { fontSize: 9, fontWeight: '700', color: '#64748b' },
  rolePillPurple: {
    backgroundColor: '#f5f3ff',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  rolePillPurpleText: { fontSize: 9, fontWeight: '800', color: '#7c3aed' },
  rolePillSky: {
    backgroundColor: '#f0f9ff',
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  rolePillSkyText: { fontSize: 9, fontWeight: '800', color: '#0284c7' },
  churchInputContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  churchInputNote: { fontSize: 10, color: '#64748b', marginTop: 4 },
  input: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 12,
    height: 38,
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '600',
  },
  twoColRow: { flexDirection: 'row' },
  inputGroup: { marginBottom: 8 },
  passwordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 12,
    height: 38,
  },
  passwordInput: { flex: 1, fontSize: 12, color: '#0f172a', padding: 0 },
  eyeBtn: { padding: 4 },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  removeBtn: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6 },
  removeBtnText: { fontSize: 12, fontWeight: '700', color: '#ef4444' },
  bottomRightGroup: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cancelBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, backgroundColor: '#f1f5f9' },
  cancelBtnText: { fontSize: 12, fontWeight: '700', color: '#64748b' },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#7c3aed',
  },
  saveBtnText: { fontSize: 12, fontWeight: '800', color: '#ffffff' },
});
