import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  navBackBtn: { padding: 6, borderRadius: 10, backgroundColor: '#f8fafc' },
  navTitleCenter: { flex: 1, alignItems: 'center', paddingHorizontal: 12 },
  navTitleText: { fontSize: 15, fontWeight: '800', color: '#0f172a', letterSpacing: -0.2 },
  navMetaSub: { fontSize: 11, color: '#64748b', fontWeight: '500', marginTop: 1 },
  navActionBtn: { padding: 6, borderRadius: 10, backgroundColor: '#f8fafc' },

  filterSection: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    gap: 8,
  },
  quickBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressPill: {
    backgroundColor: '#f8fafc',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  progressPillText: { fontSize: 11, fontWeight: '700', color: '#475569' },
  addBtnSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7c3aed',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  addBtnSmallText: { fontSize: 11, fontWeight: '700', color: '#ffffff' },
  cloneBtnSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
    paddingHorizontal: 9,
    paddingVertical: 4.5,
    borderRadius: 8,
  },
  cloneBtnSmallText: { fontSize: 11, fontWeight: '700', color: '#7c3aed' },

  searchBarWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 10,
    height: 36,
  },
  searchBarInput: { flex: 1, fontSize: 12, color: '#0f172a' },

  segmentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    padding: 2,
  },
  segmentTab: {
    flex: 1,
    paddingVertical: 4.5,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
  },
  segmentTabActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  segmentTabText: { fontSize: 11, fontWeight: '600', color: '#64748b' },
  segmentTabTextActive: { color: '#0f172a', fontWeight: '700' },

  listContent: { paddingHorizontal: 16, paddingTop: 10, gap: 6 },
  trackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 1,
  },
  trackCardActive: { borderColor: '#fca5a5', backgroundColor: '#fffbfa' },
  trackIndexBox: { width: 24, marginRight: 10 },
  artworkThumb: { width: 36, height: 36, borderRadius: 8, backgroundColor: '#e2e8f0', marginRight: 10 },
  trackIndexNum: { fontSize: 12, fontWeight: '800', color: '#94a3b8', fontVariant: ['tabular-nums'] },
  trackInfoCol: { flex: 1, minWidth: 0 },
  trackTitleText: { fontSize: 13.5, fontWeight: '700', color: '#0f172a', letterSpacing: -0.2 },
  trackMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 2.5 },
  trackSingerText: { fontSize: 11, color: '#64748b', fontWeight: '500', flexShrink: 1 },
  smallKeyChip: { backgroundColor: '#eef2ff', paddingHorizontal: 4.5, paddingVertical: 1, borderRadius: 4 },
  smallKeyChipText: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#4338ca',
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  smallTempoText: { fontSize: 10, color: '#94a3b8', fontWeight: '600' },
  trackRightCol: { flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: 10 },
  heardTouchBtn: { padding: 2 },
  heardTouchBtnActive: {},
  heardTouchBtnInactive: {},
  liveToggleBtn: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveToggleBtnActive: { backgroundColor: '#ffe4e6', borderColor: '#f43f5e' },
  liveToggleBtnInactive: { backgroundColor: '#f1f5f9', borderColor: '#e2e8f0' },
  liveToggleBtnText: { fontSize: 9.5, fontWeight: '800', letterSpacing: 0.3 },
  liveToggleBtnTextActive: { color: '#e11d48' },
  liveToggleBtnTextInactive: { color: '#94a3b8' },
  deleteTrackTouch: { padding: 4 },

  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#cbd5e1',
    alignSelf: 'center',
    marginBottom: 12,
  },

  // Category Filter Bar
  categoryBarWrap: { marginTop: 8, marginHorizontal: -16 },
  categoryBarScroll: { paddingHorizontal: 16, gap: 6, flexDirection: 'row', alignItems: 'center' },
  catChip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  catChipActive: { backgroundColor: '#7c3aed', borderColor: '#7c3aed' },
  catChipText: { fontSize: 11, fontWeight: '600', color: '#64748b' },
  catChipTextActive: { color: '#ffffff', fontWeight: '700' },
  reorderChipBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 16,
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  reorderChipText: { fontSize: 11, fontWeight: '700', color: '#7c3aed' },

  // Reorder Categories Modal
  reorderOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    justifyContent: 'flex-end',
  },
  reorderSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  reorderHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    marginBottom: 8,
  },
  reorderTitle: { fontSize: 17, fontWeight: '800', color: '#0f172a' },
  reorderSubtitle: { fontSize: 12, fontWeight: '500', color: '#64748b', marginTop: 2 },
  reorderCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reorderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginBottom: 8,
  },
  reorderRowIndex: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  reorderIndexText: { fontSize: 11, fontWeight: '800', color: '#64748b' },
  reorderCategoryName: { fontSize: 14, fontWeight: '700', color: '#0f172a' },
  reorderCategoryCount: { fontSize: 11, color: '#64748b', marginTop: 1 },
  reorderActions: { flexDirection: 'row', gap: 6 },
  arrowBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowBtnDisabled: { opacity: 0.35, backgroundColor: '#f8fafc' },
  reorderFooter: {
    flexDirection: 'row',
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    marginTop: 8,
  },
  reorderResetBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reorderResetBtnText: { fontSize: 13, fontWeight: '700', color: '#64748b' },
  reorderSaveBtn: {
    flex: 2,
    flexDirection: 'row',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#7c3aed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reorderSaveBtnText: { fontSize: 13, fontWeight: '700', color: '#ffffff' },
});
